### PR TITLE
Employee and EmployeeRoles are done

### PR DESCRIPTION
**Pull request by JavaGuru17**

### CODE REVIEW

**Comment by ismoil0709** [comment]
Why do you need role position and active fields?

**Comment by ismoil0709** [comment]
name surname fields are available in passportDetails, delete them and add gender field

**Comment by JavaGuru17** [comment]
For example we have role manager, so maybe we have also main manager. In position we can put position of role

**Comment by JavaGuru17** [comment]
Active filed need to know he is working or on vacation

**Comment by ismoil0709** [comment]
> Active filed need to know he is working or on vacation

understandable

**Comment by JavaGuru17** [comment]
Ok, I will remove them and add gender

**Comment by JavaGuru17** [comment]
Also I will remove duplicate roles

**Pull request merged**
